"""build_rir_pool.py — generate the synthetic room-impulse-response bank, offline.

WHY SYNTHETIC, NOT A MEASURED CORPUS. Three reasons, in order of weight:

  1. CONTROL. The experiment is about SOURCE-TO-MIC DISTANCE and room identity. A
     generator makes geometry, absorption and distance directly sweepable and lets every
     response carry its own measured RT60 and direct-to-reverberant ratio; a downloaded
     corpus gives whatever distances the original authors happened to measure.
  2. BANDWIDTH. This project runs at 44.1 kHz. OpenSLR26/28 simulated RIRs are 8 kHz and
     the real ones 16 kHz; resampling a 16 kHz response to 44.1 kHz turns the convolution
     into a brick-wall low-pass at 8 kHz, which is a catastrophic domain shift dressed up
     as a room. Generating at 44.1 kHz avoids that entirely.
  3. LICENSING. Survey report §3.3: EchoThief's terms are not ML-friendly, the MIT IR
     Survey archive carries no clear redistribution notice, BUT ReverbDB and OpenAIR are
     CC BY 4.0 with per-item attribution. A bank we generate is our own artifact.

And it costs little: report §2.3 (Ko et al., ICASSP 2017) MEASURED simulated image-method
rooms against 325 real RIRs on ASpIRE and found them equivalent — real RIR + point noise
34.7% WER vs synthetic medium + point noise 34.9%, and in the 5,100 h LF-MMI experiment
synthetic + point 27.0% actually beat real + isotropic 27.8%. WHAMR!'s reverberant speech
separation data is likewise pyroomacoustics shoeboxes, not measurements.

WHAT IS STORED. One stereo WAV per (room, source position), 32-bit float, at the training
sample rate, plus `manifests/parquet/rir_pool_v1.parquet` with room geometry, absorption,
source position, distance, azimuth, measured T30 and DRR, sha256 and provenance. The
loader reads ONLY the manifest at init (→ src/data/recording_aug.py:RirPool), so swapping
in a measured corpus later is a manifest change, not a code change.

TWO NORMALISATIONS MATTER and both are done here, not at train time:
  * the propagation delay to the direct arrival is REMOVED (each response is trimmed to
    its own first arrival, minus a fixed 64-sample guard that keeps the fractional-delay
    filter's pre-ringing). Without this, a source 6 m away would arrive 17 ms late and the
    ensemble's mutual timing — the thing coherent mixing exists to preserve — would be
    scrambled by a different amount per stem. The inter-CHANNEL delay is kept (both
    channels are trimmed by the earlier one's arrival), because that is the stereo cue.
  * the DIRECT PATH is normalised to unit peak, not the whole response. Report §5.1 asks
    for exactly this: peak-normalising the whole response would make a reverberant room
    quieter in its direct sound, so "far away" would arrive as "quiet" and the model could
    learn level instead of acoustics.

pyroomacoustics is MIT-licensed and is a DEV-GROUP dependency only: it is needed to build
the bank, never to train against it.

Run:
    uv run python scripts/build_rir_pool.py
      --out /home/jae.gye/storage/gugak-rir/v1
      --manifest manifests/rir_pool_v1
      --rooms 48 --positions 9 --seed 42
"""
from __future__ import annotations

import argparse
import hashlib
import math
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import soundfile

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

SPEED_OF_SOUND = 343.0
GENERATOR = "scripts/build_rir_pool.py"
LICENSE = "generated by this repository (pyroomacoustics MIT); no third-party corpus"

# Room families, one per RT60 band. Sizes are chosen so a plausible absorption reaches the
# band's reverberation time: a 0.2 s room has to be small, a 0.9 s room has to be a hall.
# INFERENCE, not measured — report §6.1 is explicit that no public RIR recipe is calibrated
# to Korean traditional instruments or to 국악당 acoustics, so these are priors from the
# speech-separation recipes (WHAMR: 5–10 × 5–10 × 3–4 m; Ko et al.: 1–10, 10–30, 30–50 m
# families) widened at the top end for a recital hall.
#
# `rt60_s` is the SABINE TARGET handed to pyroomacoustics, and it sits ABOVE the band the
# family is meant to fill, because the realised decay comes out shorter than Sabine
# predicts: air absorption is on (it is a real loss Sabine's formula ignores) and the
# image-source order is capped. The manifest therefore records both — `rt60_target_s` and
# the `rt60_s` actually MEASURED off the stored response — and the loader stratifies on the
# measured one, so nothing is ever mis-binned by this offset.
ROOM_FAMILIES = (
    dict(name="small",  rt60_s=(0.18, 0.45), length=(4.0, 8.0),   width=(3.0, 6.0),
         height=(2.5, 3.5)),
    dict(name="medium", rt60_s=(0.45, 0.90), length=(8.0, 16.0),  width=(6.0, 12.0),
         height=(3.5, 6.0)),
    dict(name="large",  rt60_s=(0.85, 1.35), length=(16.0, 26.0), width=(11.0, 18.0),
         height=(6.0, 12.0)),
)
# distance bands the loader stratifies over; every room fills the ones its walls allow
DISTANCE_BANDS_M = ((0.4, 1.2), (1.2, 3.0), (3.0, 6.0))
WALL_MARGIN_M = 0.6
DIRECT_WINDOW_MS = (0.5, 2.5)       # pre/post the first arrival, for DRR and normalisation
DIRECT_GUARD_SAMPLES = 64           # keeps the fractional-delay filter's pre-ring
FADE_MS = 10.0                      # raised-cosine fade at the truncation point


def table_paths(base: Path) -> tuple[Path, Path]:
    """Map a manifests/<name> basename to its (parquet, csv) twin paths.

    Layout rule (repo-wide): parquet = source of truth in manifests/parquet/,
    csv = eyeball copy in manifests/csv/. Both dirs are created on demand.

    Args:
        base: table basename, e.g. Path(".../manifests/rir_pool_v1").
    """
    parquet = base.parent / "parquet" / f"{base.name}.parquet"
    csv = base.parent / "csv" / f"{base.name}.csv"
    parquet.parent.mkdir(parents=True, exist_ok=True)
    csv.parent.mkdir(parents=True, exist_ok=True)
    return parquet, csv


def sample_room(rng: np.random.Generator, family: dict) -> tuple:
    """Dimensions and a feasible target RT60 for one room of `family`.

    pyroomacoustics' inverse_sabine refuses a reverberation time the geometry cannot
    reach (it would need absorption outside (0, 1]); rather than silently clamping, the
    draw is retried, which keeps the realised RT60 distribution inside the band.
    """
    import pyroomacoustics as pra
    for _ in range(64):
        dims = [float(rng.uniform(*family["length"])),
                float(rng.uniform(*family["width"])),
                float(rng.uniform(*family["height"]))]
        rt60 = float(rng.uniform(*family["rt60_s"]))
        try:
            absorption, max_order = pra.inverse_sabine(rt60, dims)
        except ValueError:
            continue
        return dims, rt60, float(absorption), int(max_order)
    raise RuntimeError(f"no feasible room found for family {family['name']}")


def sample_positions(rng: np.random.Generator, dims: list, mic_center: np.ndarray,
                     count: int) -> list:
    """Source positions cycling through the distance bands, inside the walls.

    Cycling rather than sampling the band means a room contributes to every band its
    geometry allows, so the loader's stratified distance draw is not quietly biased by
    which bands a given room happened to populate. Azimuth covers the full circle rather
    than a frontal arc so that a distant source still fits inside a small room — the
    stereo pair is omnidirectional, so "behind" is a legitimate placement.
    """
    positions = []
    for index in range(count):
        low, high = DISTANCE_BANDS_M[index % len(DISTANCE_BANDS_M)]
        for _ in range(64):
            distance = float(rng.uniform(low, high))
            azimuth = float(rng.uniform(-math.pi, math.pi))
            height = float(rng.uniform(0.8, min(1.8, dims[2] - WALL_MARGIN_M)))
            point = np.array([mic_center[0] + distance * math.cos(azimuth),
                              mic_center[1] + distance * math.sin(azimuth), height])
            if np.all(point > WALL_MARGIN_M) and np.all(point < np.array(dims)
                                                        - WALL_MARGIN_M):
                positions.append((point, distance, math.degrees(azimuth)))
                break
    return positions


def measure_t30(response: np.ndarray, sample_rate: int) -> float:
    """Schroeder-integrated T30 of the stored response, in seconds (nan if unmeasurable).

    Measured on what is actually SAVED — after truncation — so the manifest reports the
    response the model will hear, not the one the room simulator intended.
    """
    energy = (response.astype(np.float64) ** 2).sum(axis=0)
    schroeder = np.cumsum(energy[::-1])[::-1]
    if schroeder[0] <= 0:
        return float("nan")
    curve = 10.0 * np.log10(np.maximum(schroeder / schroeder[0], 1e-20))
    try:
        start = int(np.flatnonzero(curve <= -5.0)[0])
        end = int(np.flatnonzero(curve <= -35.0)[0])
    except IndexError:
        return float("nan")
    if end <= start:
        return float("nan")
    slope = (curve[end] - curve[start]) / ((end - start) / sample_rate)
    return float(-60.0 / slope) if slope < 0 else float("nan")


def trim_and_normalise(channels: np.ndarray, distance: float, sample_rate: int,
                       tail_frames: int) -> tuple:
    """Remove the propagation delay, normalise the direct path, truncate → (2, tail), DRR.

    The first arrival is located analytically (fs·d/c plus pyroomacoustics' fractional
    delay offset) and then refined by an argmax inside a ±2 ms search, so a strong early
    reflection cannot be mistaken for the direct sound.
    """
    import pyroomacoustics as pra
    expected = int(round(sample_rate * distance / SPEED_OF_SOUND)
                   + pra.constants.get("frac_delay_length") // 2)
    search = int(round(0.002 * sample_rate))
    low = max(0, expected - search)
    high = min(channels.shape[1], expected + search + 1)
    if high <= low:
        return None, float("nan")
    peaks = [low + int(np.argmax(np.abs(channels[c, low:high])))
             for c in range(channels.shape[0])]
    first = max(0, min(peaks) - DIRECT_GUARD_SAMPLES)

    pre = int(round(DIRECT_WINDOW_MS[0] * sample_rate / 1000.0))
    post = int(round(DIRECT_WINDOW_MS[1] * sample_rate / 1000.0))
    direct_lo = max(0, min(peaks) - pre)
    direct_hi = min(channels.shape[1], max(peaks) + post)
    direct_peak = float(np.abs(channels[:, direct_lo:direct_hi]).max())
    if direct_peak <= 0:
        return None, float("nan")

    direct_energy = float((channels[:, direct_lo:direct_hi] ** 2).sum())
    total_energy = float((channels[:, first:] ** 2).sum())
    reverb_energy = max(total_energy - direct_energy, 1e-30)
    drr_db = 10.0 * math.log10(direct_energy / reverb_energy)

    trimmed = channels[:, first:first + tail_frames] / direct_peak
    out = np.zeros((2, tail_frames), dtype=np.float32)
    out[:, :trimmed.shape[1]] = trimmed[:2]
    if trimmed.shape[1] >= tail_frames:            # truncated: fade so there is no click
        fade = int(round(FADE_MS * sample_rate / 1000.0))
        ramp = 0.5 * (1.0 + np.cos(np.linspace(0.0, math.pi, fade)))
        out[:, -fade:] *= ramp.astype(np.float32)
    return out, drr_db


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the synthetic RIR bank.")
    ap.add_argument("--out", default="/home/jae.gye/storage/gugak-rir/v1",
                    help="WAV output root (data — deliberately outside the repo)")
    ap.add_argument("--manifest", default="manifests/rir_pool_v1",
                    help="table BASENAME under manifests/ (parquet + csv twin)")
    ap.add_argument("--rooms", type=int, default=48)
    ap.add_argument("--positions", type=int, default=9)
    ap.add_argument("--sample-rate", type=int, default=44100)
    ap.add_argument("--tail-seconds", type=float, default=1.0)
    ap.add_argument("--max-order", type=int, default=8,
                    help="image-source order cap; the late field comes from ray tracing")
    ap.add_argument("--no-ray-tracing", action="store_true")
    ap.add_argument("--n-rays", type=int, default=20000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    import pyroomacoustics as pra

    rng = np.random.default_rng(args.seed)
    out_root = Path(args.out)
    out_root.mkdir(parents=True, exist_ok=True)
    tail_frames = int(round(args.tail_seconds * args.sample_rate))

    rows = []
    started = time.time()
    for room_index in range(args.rooms):
        family = ROOM_FAMILIES[room_index % len(ROOM_FAMILIES)]
        dims, rt60_target, absorption, sabine_order = sample_room(rng, family)
        max_order = min(sabine_order, args.max_order)

        # STEREO IS A REQUIREMENT, NOT A DETAIL. The stems are close-miked and near-mono
        # (measured per-class L/R correlation .96–.99 for seven of the nine classes; 가야금
        # .67 and 양금 .66 are wide zithers on a spaced pair, i.e. source width, not room).
        # Convolving both channels with the SAME response would leave the correlation at
        # ~1.0 — a "mono room", which is not what a distant stereo capture sounds like,
        # because its late field is decorrelated. So the array is TWO microphone positions
        # in one room and the loader convolves L with h_L and R with h_R.
        # The spacing spans the real devices this has to cover: ~6 cm is a phone, 15–25 cm
        # a handheld recorder or an ORTF-ish pair, 45 cm a spaced main pair. A single wide
        # setting would decorrelate everything to a concert-hall extreme.
        spacing = float(rng.uniform(0.06, 0.45))
        mic_center = np.array([
            float(rng.uniform(WALL_MARGIN_M, dims[0] - WALL_MARGIN_M)),
            float(rng.uniform(WALL_MARGIN_M, dims[1] - WALL_MARGIN_M)),
            float(rng.uniform(1.2, min(1.8, dims[2] - WALL_MARGIN_M)))])
        mics = np.c_[mic_center + np.array([0.0, -spacing / 2, 0.0]),
                     mic_center + np.array([0.0, +spacing / 2, 0.0])]
        positions = sample_positions(rng, dims, mic_center, args.positions)
        if not positions:
            continue

        room = pra.ShoeBox(dims, fs=args.sample_rate,
                           materials=pra.Material(absorption), max_order=max_order,
                           air_absorption=True, ray_tracing=not args.no_ray_tracing)
        if not args.no_ray_tracing:
            room.set_ray_tracing(receiver_radius=0.5, n_rays=args.n_rays,
                                 energy_thres=1e-7)
        room.add_microphone_array(pra.MicrophoneArray(mics, args.sample_rate))
        for point, _, _ in positions:
            room.add_source(point)
        room.compute_rir()

        room_id = f"room{room_index:03d}"
        for position_index, (point, distance, azimuth) in enumerate(positions):
            length = max(len(room.rir[c][position_index]) for c in (0, 1))
            channels = np.zeros((2, length), dtype=np.float64)
            for channel in (0, 1):
                response = room.rir[channel][position_index]
                channels[channel, :len(response)] = response
            stored, drr_db = trim_and_normalise(channels, distance, args.sample_rate,
                                                tail_frames)
            if stored is None:
                continue
            relative = f"{room_id}/pos{position_index:02d}.wav"
            path = out_root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            soundfile.write(path, stored.T, args.sample_rate, subtype="FLOAT")
            rows.append(dict(
                room_id=room_id, position=position_index, path=relative,
                family=family["name"], room_x=dims[0], room_y=dims[1], room_z=dims[2],
                absorption=absorption, max_order=max_order,
                rt60_target_s=rt60_target,
                rt60_s=measure_t30(stored, args.sample_rate),
                drr_db=drr_db, distance_m=distance, azimuth_deg=azimuth,
                source_z=float(point[2]), mic_spacing_m=spacing,
                mic_x=float(mic_center[0]), mic_y=float(mic_center[1]),
                mic_z=float(mic_center[2]),
                frames=int(stored.shape[1]), sample_rate=args.sample_rate,
                sha256=hashlib.sha256(stored.tobytes()).hexdigest(),
                generator=GENERATOR, license=LICENSE, seed=args.seed,
                pyroomacoustics=pra.__version__))
        print(f"{room_id} {family['name']:6s} dims={np.round(dims,1).tolist()} "
              f"a={absorption:.3f} order={max_order} "
              f"positions={len(positions)} [{time.time()-started:6.1f}s]", flush=True)

    table = pd.DataFrame(rows)
    # a response whose T30 could not be measured cannot be stratified; drop it loudly
    unmeasurable = int(table.rt60_s.isna().sum())
    if unmeasurable:
        print(f"dropping {unmeasurable} responses with an unmeasurable T30")
        table = table[table.rt60_s.notna()].reset_index(drop=True)
    parquet_path, csv_path = table_paths(REPO_ROOT / args.manifest)
    table.to_parquet(parquet_path, index=False)
    table.to_csv(csv_path, index=False)

    print(f"\n{len(table)} responses over {table.room_id.nunique()} rooms -> {out_root}")
    print(f"manifest -> {parquet_path}")
    for family in ROOM_FAMILIES:
        subset = table[table.family == family["name"]]
        if subset.empty:
            continue
        print(f"  {family['name']:6s} n={len(subset):4d} "
              f"T30 {subset.rt60_s.min():.2f}–{subset.rt60_s.max():.2f} s · "
              f"DRR {subset.drr_db.min():+.1f}–{subset.drr_db.max():+.1f} dB · "
              f"distance {subset.distance_m.min():.1f}–{subset.distance_m.max():.1f} m")


if __name__ == "__main__":
    main()
