"""recording_aug.py — recording-condition augmentation (the `gugak_mix.recording_aug` block).

WHY THIS EXISTS. 71955 was captured in ONE studio. Every stem of every song shares the
same room, the same close-miking and the same chain, so the corpus has effectively zero
INTER-RECORDING acoustic variance — and cross-song incoherent mixing manufactures none,
because every song it draws from was recorded under identical conditions. MUSDB gets that
diversity for free (its songs come from many studios); we have to synthesize it. A model
trained here only ever sees one acoustic path, and deployment audio is not close-miked:
it is picked up at some distance, in an unknown room. Supplying that missing axis is what
this module is for, and room simulation is rank 1 for that reason, NOT because reverb per
se is the deployment problem.

THE SYMMETRIC MISTAKE, avoided by design: do not manufacture variance in the dimension the
corpus is RIGHT about. A real recording puts every instrument in ONE space behind ONE
acoustic path, so giving each stem its own room would hand the separator a "which room is
this" cue that is perfectly informative in training and simply absent at test time. The
room therefore varies ACROSS mixtures and is SHARED WITHIN one (→ RirConfig).

Five stages, each independently gated, each with an explicit target policy (the algebra is
in the survey report §4; evidence classes below are its convention — MEASURED = a paper
reports a controlled comparison, RECIPE = a released generator demonstrates the synthesis,
INFERENCE = derived from those plus the sum algebra, i.e. not a reported Gugak result):

  1. device / capture response — per-stem minimum-phase biquad cascade. Linear, so
     T(Σ s_i) = Σ T(s_i): apply to every target and the sum survives untouched.
     COUPLED TO DISTANCE by default (→ DeviceResponseConfig).
  2. room  — convolution with a synthetic RIR bank. `source_image` targets (h_i * s_i,
     mixture Σ_i h_i * s_i) keep the sum EXACT for any choice of h_i, so the scope knob
     is free to be whatever is physically right rather than whatever the algebra allows;
     the default is one shared h per mixture. `dry_source` is the dereverberation task and
     is a separate coherence_mode, never a default.
  3. level automation — a gain envelope shared by mixture and every target (capture-level
     drift), or independent per stem (fader/production drift). Both sum-preserving,
     because the mixture is rebuilt as the sum AFTER the envelope is applied.
  4. mix-bus loudness + limiting (LimitAug) — the only NONLINEAR stage. D(Σ s_i) ≠ Σ D(s_i),
     so targets are bus-affected source images: r[t] = m'[t]/m[t] where the mixture is
     above the silence floor, y_i = r·s_i, and the float residual m' − Σ y_i is pushed
     onto the largest stem at each sample so the sum is exact again (report §4.3).
  5. dirty input — noise / resample / quantize / clip on the MIXTURE ONLY, targets clean.
     This DELIBERATELY breaks mixture ≡ Σ targets and is reachable only under
     `coherence_mode: clean_under_degraded_input`.

OFF IS FREE. An absent or `enable: false` block draws not one value from the item RNG and
runs not one line of the realisation path, so every pre-existing config (exp003.x, exp004.x,
exp006) stays bit-identical — proved against the pre-change module by
tests/test_recording_aug.py::test_off_by_default_is_bit_identical. Within an enabled block
each stage with probability 0 likewise consumes nothing, following the convention
`GugakMixDataset._draw_coherent_count` already set for p = 0.

ALL RANDOMNESS IS DRAWN IN THE PLAN. `RecordingAugmenter.plan()` is called from
`GugakMixDataset._plan_item` with the item's `np.random.default_rng([seed, index])` and
returns a fully-decided `RecordingPlan`; the realisation half touches no RNG. Audio is
never read at plan time, so `plan_item()` still works with no RIR bank on disk.

LICENSING. Everything here is NumPy/SciPy (BSD) plus soundfile (BSD-3). The RIR bank is
generated by scripts/build_rir_pool.py with pyroomacoustics (MIT) and is therefore our own
artifact with no third-party corpus terms attached — report §3.3 flags that the licence
situation of the measured corpora (EchoThief unusable, MIT IR Survey unclear, BUT/OpenAIR
attribution-bound) needs an audit before shipping. Pedalboard (GPLv3) is deliberately NOT
used by any stage added here; the existing stem/mix-bus EQ still uses it.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import NamedTuple

import numpy as np
import pandas as pd
import scipy.fft
import scipy.ndimage
import scipy.signal
import soundfile
import soxr

COHERENCE_MODES = ("strict_sum", "dereverberation", "clean_under_degraded_input")
RIR_SCOPES = ("per_mixture", "per_cluster", "per_stem")
POSITION_SCOPES = ("shared", "per_cluster", "per_stem")
RIR_TARGET_MODES = ("source_image", "dry_source")
LOUDNESS_MODES = ("fixed", "sampled")


# --- config -----------------------------------------------------------------
def _reject_unknown(cls, mapping: dict, label: str) -> dict:
    """Unknown keys in a nested YAML sub-block are an error, never a silent no-op.

    Same contract as MixDatasetConfig.from_mapping and LoudnessMatchConfig.from_mapping:
    a typo in an experiment config must stop the run, not quietly train the wrong arm.
    """
    unknown = set(mapping) - {f for f in cls.__dataclass_fields__}
    if unknown:
        raise KeyError(f"unknown {label} config keys: {sorted(unknown)}")
    return dict(mapping)


@dataclass
class DeviceResponseConfig:
    """Stage 1 — the microphone/preamp transfer function, as a biquad cascade.

    COUPLED TO DISTANCE (`couple_to_distance`, default true) because that is the physics
    the experiment is about: a directional capsule up close gives a proximity low-shelf
    lift, and that lift disappears as the source moves away while HF air absorption and
    the capsule's off-axis rolloff take over. Drawing the shelf independently of the room
    would put a +6 dB proximity boost on a stem recorded 6 m away, which is exactly the
    kind of physically impossible combination that teaches the model nothing.

    ITS GRAIN FOLLOWS THE ROOM'S SOURCE POSITIONS, so under the defaults there is exactly
    ONE device response per mixture, shared by every stem — one microphone, one preamp,
    one ensemble. Giving each stem its own capsule would reintroduce the per-stem cue that
    RirConfig's docstring explains we must not invent. The per-INSTRUMENT half of the
    microphone problem — where the mic was pointed, a 가야금 taken at the bridge versus at
    the soundhole — is a property of one (mic, instrument) pair and belongs to the existing
    per-stem EQ board (`eq_stem_prob`), which is exactly a smooth random spectral transform
    per stem and is the better-MEASURED of the two.

    THIS STAGE IS NOT A CHEAP EXTRA NEXT TO THE ROOM. Measurement on the ingested store
    (per-class L/R correlation .96–.99 for seven of the nine classes) says the stems carry
    almost no diffuse field, so the corpus's invariant acoustic fingerprint is THE
    MICROPHONE AND WHERE IT WAS PUT — a spectral colouration — not a reverberant tail. An
    added room multiplies a new magnitude response on top of that colouration; it cannot
    make the colouration vary. Only a random spectral transform can. Hence the real range
    below: a broadband tilt plus one to three resonances, not a single token peak.

    Evidence: report §2.3 has no controlled proximity-effect augmentation anywhere in the
    checked literature and gives the low-shelf approximation (cutoff 80–250 Hz, gain
    0–6 dB) as an INFERENCE from close-microphone directivity, not a measured range.
    The high-shelf air term and the capsule resonance are likewise INFERENCE. The device
    stage as a class is RECIPE-backed (DCASE TAU22 device IRs at p .2–.6, MicIRP vintage
    capsules — report §2.3), but those are classification results with input-only
    convolution, so the numbers here are deliberately mild: report §5.1 says "start with
    broad ±3 dB/octave, not a 20 dB telephone filter".
    """
    prob: float = 0.0
    # every real capsule/preamp rolls off the bottom somewhere; log-uniform
    highpass_hz: list = field(default_factory=lambda: [20.0, 120.0])
    # broadband tilt — the coarsest axis along which two microphones differ (dark against
    # bright), realised as a matched low/high shelf pair of ±tilt_max_db/2 about a pivot
    tilt_max_db: float = 5.0
    tilt_pivot_hz: list = field(default_factory=lambda: [700.0, 2000.0])
    # proximity effect: full `proximity_max_db` at `proximity_ref_distance_m`, decaying
    # to 0 dB by `proximity_null_distance_m` (INFERENCE — report §2.3)
    proximity_shelf_hz: list = field(default_factory=lambda: [80.0, 250.0])
    proximity_max_db: float = 6.0
    proximity_ref_distance_m: float = 0.6
    proximity_null_distance_m: float = 2.5
    # air absorption / off-axis HF loss: 0 dB at the reference distance, growing to
    # `air_max_db` of ATTENUATION at `air_full_distance_m`
    air_shelf_hz: list = field(default_factory=lambda: [6000.0, 14000.0])
    air_max_db: float = 6.0
    air_full_distance_m: float = 6.0
    # capsule/off-axis resonances: 1–3 peaks over the band where capsules actually differ.
    # One peak cannot represent a presence lift AND a mid scoop; three can. INFERENCE, but
    # the shape family is the one MicIRP's 65 vintage capsules show (report §2.3).
    capsule_peaks: list = field(default_factory=lambda: [1, 3])
    capsule_hz: list = field(default_factory=lambda: [300.0, 12000.0])
    capsule_max_db: float = 5.0
    capsule_q: list = field(default_factory=lambda: [0.7, 3.0])
    # hard ceiling on any single filter's gain, so a config typo cannot make a telephone
    max_gain_db: float = 9.0
    # true = read the stem's sampled source-to-mic distance (needs the room stage);
    # false = draw a distance from `fallback_distance_m` and use the same curves
    couple_to_distance: bool = True
    fallback_distance_m: list = field(default_factory=lambda: [0.3, 3.0])

    @classmethod
    def from_mapping(cls, mapping: dict) -> "DeviceResponseConfig":
        return cls(**_reject_unknown(cls, mapping, "recording_aug.device_response"))


@dataclass
class RirConfig:
    """Stage 2 — room convolution. THE experiment: inter-MIXTURE acoustic variance.

    WHAT 71955 IS MISSING, PRECISELY. It lacks INTER-RECORDING acoustic variance: one
    studio, one miking, for every song, so cross-song mixing manufactures none. It does
    NOT lack intra-recording per-instrument variance, and we must not invent any. A real
    recording has every instrument in ONE space captured through ONE acoustic path, so a
    model handed a different room per stem can separate by "which room is this" — a cue
    that is perfectly informative in training and absent at test time. That is the classic
    way an augmentation makes a model worse. Hence:

      VARY THE ROOM ACROSS MIXTURES. SHARE IT WITHIN A MIXTURE.

    `scope` — which stems share a ROOM:

      per_mixture  DEFAULT, and the exp007 arm. One room, one transfer function h drawn
                   per mixture, applied identically to every stem:
                       y_i = h * s_i      x = Σ_i y_i = h * (Σ_i s_i)
                   Shared h plus linearity makes the sum EXACT, and it is also the
                   cheapest option in the whole module — ONE kernel spectrum multiplied
                   across the batched (n_stems, channels, time) transform, not nine.
      per_cluster  a room per coherent cluster; independently drawn incoherent stems may
                   take their own. Defensible ONLY because incoherent mixing already
                   combines sources that never co-occurred — but it still hands the model
                   a room cue for the incoherent half. A second arm at most.
      per_stem     ⚠️ a different room per stem. Implemented so the ablation exists. It
                   introduces a TRAIN-ONLY separation cue that does not exist in any real
                   recording. Not the default, not exp007. Do not reach for it because it
                   "adds more diversity" — the diversity is in the wrong dimension.

    `position_scope` — source-position variation WITHIN a shared room. Physically real
    (instruments in an ensemble sit at different distances and angles from one mic pair,
    so they differ in DRR and early reflections while sharing the room's late field), but
    it is a REFINEMENT, not the first experiment, so it defaults to `shared`: one position
    for the whole room group, i.e. literally one kernel per mixture. `per_cluster` and
    `per_stem` open it up, in that order of safety.

    Evidence: room simulation for separation is RECIPE-strong (WHAMR pyroomacoustics
    shoeboxes, SMS-WSJ, DNS) and MEASURED for reverberant speech separation
    (Aralikatti et al.: real-RIR addition +34% SI-SDRi without pretraining) and for
    far-field ASR (Ko et al.: ASpIRE dev WER real RIR+point 34.7% vs synthetic medium+point
    34.9% — synthetic matched measured, which is why a synthetic bank is not a compromise
    here). Direct nine-stem MUSIC SDR evidence does not exist; report §6.1 is explicit that
    no public RIR recipe is calibrated to Korean traditional instruments.

    Stratification is by BOTH RT60 and source-to-mic DISTANCE, and the bank stores the
    measured direct-to-reverberant ratio per response, because DRR — not RT60 — is what
    "it was picked up from a distance rather than close-miked" actually changes. The
    distance band is drawn once per ROOM, so under the defaults there is exactly one
    sampled distance per mixture: one ensemble, one mic, one placement.
    """
    prob: float = 0.0
    # the bank (→ scripts/build_rir_pool.py). `manifest` is repo-relative like every other
    # manifest; `audio_root` is ABSOLUTE and lives outside the repo (the WAVs are data).
    manifest: str = "manifests/parquet/rir_pool_v1.parquet"
    audio_root: str = "/home/jae.gye/storage/gugak-rir/v1"
    scope: str = "per_mixture"
    position_scope: str = "shared"
    target_mode: str = "source_image"
    # uniform over bands, then uniform within the band's members: stratified exposure, so
    # a bank that happens to hold more small rooms does not become a small-room prior
    rt60_bands_s: list = field(default_factory=lambda: [[0.15, 0.35], [0.35, 0.65],
                                                        [0.65, 1.00]])
    distance_bands_m: list = field(default_factory=lambda: [[0.4, 1.2], [1.2, 3.0],
                                                            [3.0, 6.0]])
    # responses longer than this are not in the bank; the loader asserts it
    max_tail_seconds: float = 1.0
    # worker-local LRU over the precomputed kernel spectra. One entry is
    # 2 × (nfft/2+1) × 8 B ≈ 3.1 MB at the 8 s chunk, so 8 entries ≈ 25 MB per worker.
    fft_cache_size: int = 8

    @classmethod
    def from_mapping(cls, mapping: dict) -> "RirConfig":
        cfg = cls(**_reject_unknown(cls, mapping, "recording_aug.rir"))
        if cfg.scope not in RIR_SCOPES:
            raise ValueError(f"recording_aug.rir.scope={cfg.scope!r}: expected {RIR_SCOPES}")
        if cfg.position_scope not in POSITION_SCOPES:
            raise ValueError(f"recording_aug.rir.position_scope={cfg.position_scope!r}: "
                             f"expected {POSITION_SCOPES}")
        if cfg.target_mode not in RIR_TARGET_MODES:
            raise ValueError(f"recording_aug.rir.target_mode={cfg.target_mode!r}: "
                             f"expected {RIR_TARGET_MODES}")
        return cfg


@dataclass
class LevelAutomationConfig:
    """Stage 3 — time-varying recording level, linear in dB between breakpoints.

    `mixbus_prob` is the CAPTURE-level envelope: one a[t] on every stem, so the mixture
    hears it too and the sum is exact. `stem_prob` is the production/fader reading: an
    independent envelope per stem, still sum-preserving because the mixture is rebuilt
    after the envelopes are applied, but it models a different physical thing and is off
    by default.

    Evidence: INFERENCE. Report ranks this 4th and is explicit that no checked paper gives
    a controlled MSS SDR gain for level automation; audiomentations GainTransition
    (−24..+6 dB over 0.2–6 s) and sdx23-aimless RandomVolumeAutomation (segments ≥3 s,
    ±6 dB, Dirichlet lengths, linear-dB transitions) are the RECIPE the ranges copy.
    """
    mixbus_prob: float = 0.0
    stem_prob: float = 0.0
    segments_min: int = 2
    segments_max: int = 5
    min_segment_seconds: float = 2.0
    gain_db_min: float = -6.0
    gain_db_max: float = 6.0

    @classmethod
    def from_mapping(cls, mapping: dict) -> "LevelAutomationConfig":
        return cls(**_reject_unknown(cls, mapping, "recording_aug.level_automation"))


@dataclass
class LimitAugConfig:
    """Stage 4 — mix-bus loudness and limiting (LimitAug), the only nonlinear stage.

    Evidence: the best-MEASURED technique in the whole report (Jeon & Lee, ISMIR 2022:
    LimitAug recovers ~.22–.85 dB of the musdb-L/XL out-of-domain loss and can improve
    in-domain). It is implemented here in full BECAUSE it is cheap and well-measured —
    but it models loudness-war MASTERING mismatch, a POST-PRODUCTION axis, and the
    deployment gap this project is chasing is CAPTURE-side. It is therefore off in exp007.

    THE NORMALIZATION ORDER IS THE TRAP. `GugakMixDataset._normalize` returns every
    mixture to −19 LUFS. Run after the limiter it erases exactly the loudness diversity
    LimitAug exists to create, leaving only the limiter's waveform distortion — report
    §5.1 flags this explicitly. Hence:
      loudness_mode: sampled   draw the PRE-bus target loudness per item, N(mean, std)
      normalize_after_bus: false   the post-bus operation is a shared peak guard only
    Setting `loudness_mode: fixed` + `normalize_after_bus: true` reproduces the old
    behaviour and gives the "limiter shape without loudness shift" control arm.

    Ranges: target loudness N(−14, 2) LUFS is report §5.1's first-Gugak-arm suggestion
    (N(−10.9, 1.2) is the loud-broadcast match, measured from musdb-L); threshold 0 dBFS
    and release U(30, 200) ms are the paper's own settings.
    """
    prob: float = 0.0
    loudness_mode: str = "fixed"
    target_lufs_mean: float = -14.0
    target_lufs_std: float = 2.0
    threshold_dbfs: float = 0.0
    release_ms: list = field(default_factory=lambda: [30.0, 200.0])
    attack_ms: float = 1.5
    normalize_after_bus: bool = True
    residual_correction: bool = True

    @classmethod
    def from_mapping(cls, mapping: dict) -> "LimitAugConfig":
        cfg = cls(**_reject_unknown(cls, mapping, "recording_aug.limit_aug"))
        if cfg.loudness_mode not in LOUDNESS_MODES:
            raise ValueError(f"recording_aug.limit_aug.loudness_mode="
                             f"{cfg.loudness_mode!r}: expected {LOUDNESS_MODES}")
        return cfg


@dataclass
class DirtyInputConfig:
    """Stage 5 — degrade the MIXTURE, keep the targets clean. Breaks the sum on purpose.

    Unreachable unless `coherence_mode: clean_under_degraded_input`, and every probability
    defaults to 0 on top of that, so it takes two deliberate edits to turn on. The task it
    defines is separation PLUS denoising/restoration, scored against a different invariant
    (report §4.4), and it must never be mixed into a strict-sum comparison by accident.

    Evidence: LOW-to-MEDIUM. Cross-corpus speech work gets about +.6–1.4 dB from robust
    mixing combinations (Alex et al.), and DNS/WHAM establish the recipe, but report §2.3
    found NO controlled music-separation paper that trains with a codec and reports
    codec-held-out SDR. The numeric ranges are report §5.1's mild starting values.

    CODEC IS DELIBERATELY NOT IMPLEMENTED — `codec_prob > 0` raises. Reasons, in order:
    no measured MSS evidence exists (§2.3); the local measurement is 140–170 ms per 8 s
    item (§3.5), which alone exceeds the entire per-item CPU budget; and MP3/AAC/Opus need
    an ffmpeg and licence audit (§6.1). It is a reserved seam in the repo's sense.
    """
    noise_prob: float = 0.0
    noise_manifest: str | None = None
    noise_audio_root: str | None = None
    noise_snr_db: list = field(default_factory=lambda: [15.0, 35.0])
    resample_prob: float = 0.0
    intermediate_rates: list = field(default_factory=lambda: [16000, 24000, 32000])
    quantize_prob: float = 0.0
    bit_depths: list = field(default_factory=lambda: [12, 16])
    clip_prob: float = 0.0
    clip_dbfs: list = field(default_factory=lambda: [-3.0, -1.0])
    codec_prob: float = 0.0        # reserved seam — nonzero raises (see docstring)

    @classmethod
    def from_mapping(cls, mapping: dict) -> "DirtyInputConfig":
        return cls(**_reject_unknown(cls, mapping, "recording_aug.dirty_input"))

    @property
    def any_enabled(self) -> bool:
        return max(self.noise_prob, self.resample_prob, self.quantize_prob,
                   self.clip_prob, self.codec_prob) > 0.0


@dataclass
class RecordingAugConfig:
    """The `gugak_mix.recording_aug` block. Absent/empty = disabled = byte-identical."""
    enable: bool = False
    # strict_sum              mixture ≡ Σ targets to float tolerance. The only mode any
    #                         existing experiment may use.
    # dereverberation         RIR targets are the DRY stems; the mixture is the sum of the
    #                         wet images. A different TASK, not an augmentation.
    # clean_under_degraded_input   stage 5. The mixture is degraded, the targets are not.
    coherence_mode: str = "strict_sum"
    # the project's silence tolerance (CLAUDE.md: post-ingest silence is a ±1-LSB residue
    # at 1.192e-07, so anything ≥1e-6 is safely above it). Used as the mixture-support
    # floor in the LimitAug ratio and as the sum-invariant assertion tolerance.
    silence_eps: float = 1e-6
    # assert the invariant on every item. Cheap (one reduction), but it is a debug aid:
    # leave it off for production runs and on for smoke/bench.
    assert_invariant: bool = False
    device_response: dict = field(default_factory=dict)
    rir: dict = field(default_factory=dict)
    level_automation: dict = field(default_factory=dict)
    limit_aug: dict = field(default_factory=dict)
    dirty_input: dict = field(default_factory=dict)

    @classmethod
    def from_mapping(cls, mapping: dict) -> "RecordingAugConfig":
        return cls(**_reject_unknown(cls, mapping, "recording_aug"))


@dataclass(frozen=True)
class ResolvedRecordingConfig:
    """The block with its five sub-blocks parsed and cross-validated."""
    enable: bool
    coherence_mode: str
    silence_eps: float
    assert_invariant: bool
    device: DeviceResponseConfig
    rir: RirConfig
    automation: LevelAutomationConfig
    limit: LimitAugConfig
    dirty: DirtyInputConfig

    @classmethod
    def from_mapping(cls, mapping: dict) -> "ResolvedRecordingConfig":
        block = RecordingAugConfig.from_mapping(mapping)
        resolved = cls(enable=bool(block.enable),
                       coherence_mode=str(block.coherence_mode),
                       silence_eps=float(block.silence_eps),
                       assert_invariant=bool(block.assert_invariant),
                       device=DeviceResponseConfig.from_mapping(block.device_response),
                       rir=RirConfig.from_mapping(block.rir),
                       automation=LevelAutomationConfig.from_mapping(
                           block.level_automation),
                       limit=LimitAugConfig.from_mapping(block.limit_aug),
                       dirty=DirtyInputConfig.from_mapping(block.dirty_input))
        resolved.validate()
        return resolved

    def validate(self) -> None:
        """Cross-block rules. The two sum-breaking modes must be unreachable by accident."""
        if self.coherence_mode not in COHERENCE_MODES:
            raise ValueError(f"recording_aug.coherence_mode={self.coherence_mode!r}: "
                             f"expected {COHERENCE_MODES}")
        if not self.enable:
            return
        if self.dirty.codec_prob > 0.0:
            raise NotImplementedError(
                "recording_aug.dirty_input.codec_prob > 0: codec simulation is a reserved "
                "seam. No controlled music-separation experiment isolating MP3/AAC/Opus "
                "exists (report §2.3), the local round-trip costs 140–170 ms per 8 s item "
                "(§3.5) — the whole per-item budget — and it needs an ffmpeg/licence audit.")
        wants_dry = self.rir.target_mode == "dry_source"
        if self.coherence_mode == "strict_sum":
            if wants_dry:
                raise ValueError(
                    "rir.target_mode='dry_source' under coherence_mode='strict_sum': dry "
                    "targets against a reverberant mixture are separation PLUS "
                    "dereverberation and do NOT satisfy mixture ≡ Σ targets. Set "
                    "coherence_mode: dereverberation if that is really the task.")
            if self.dirty.any_enabled:
                raise ValueError(
                    "recording_aug.dirty_input has a nonzero probability under "
                    "coherence_mode='strict_sum': noise/resample/quantize/clip degrade the "
                    "MIXTURE ONLY and intentionally break mixture ≡ Σ targets. Set "
                    "coherence_mode: clean_under_degraded_input to opt in.")
        elif self.coherence_mode == "dereverberation":
            if not wants_dry or self.rir.prob <= 0.0:
                raise ValueError(
                    "coherence_mode='dereverberation' needs rir.prob > 0 and "
                    "rir.target_mode='dry_source' — otherwise it is an ordinary strict-sum "
                    "arm mislabelled as a different task.")
            if self.dirty.any_enabled:
                raise ValueError("dirty_input needs coherence_mode="
                                 "'clean_under_degraded_input', not 'dereverberation'")
        if self.rir.prob > 0.0 and not 0.0 < self.rir.max_tail_seconds <= 3.0:
            raise ValueError(f"rir.max_tail_seconds={self.rir.max_tail_seconds}: expected "
                             "(0, 3] s — longer tails blow the FFT budget (report §3.5)")

    @property
    def any_stage_enabled(self) -> bool:
        return self.enable and max(
            self.device.prob, self.rir.prob, self.automation.mixbus_prob,
            self.automation.stem_prob, self.limit.prob,
            1.0 if self.limit.loudness_mode == "sampled" else 0.0,
            self.dirty.noise_prob, self.dirty.resample_prob, self.dirty.quantize_prob,
            self.dirty.clip_prob) > 0.0


# --- plan objects (decided in plan_item, realised in __getitem__) -----------
class RirAssignment(NamedTuple):
    """One bank response and the output slots that are convolved with it."""
    row: int                 # index into RirPool.table
    slots: tuple
    distance_m: float
    rt60_s: float
    drr_db: float


class RirItemPlan(NamedTuple):
    """The room decision for one mixture: one room, one or more source positions."""
    room_id: str
    assignments: tuple       # tuple[RirAssignment]
    target_mode: str


class EnvelopePlan(NamedTuple):
    """One linear-in-dB gain envelope; `slots=None` = shared by every stem."""
    times_s: tuple
    gains_db: tuple
    slots: tuple | None


class BusPlan(NamedTuple):
    """Stage 4. `release_ms=None` = the loudness draw fired but the limiter did not."""
    target_lufs: float
    release_ms: float | None
    attack_ms: float
    threshold_dbfs: float
    normalize_after_bus: bool
    residual_correction: bool


class DirtyPlan(NamedTuple):
    """Stage 5. Every field None = that degradation did not fire."""
    noise_row: int | None
    noise_start: int
    noise_snr_db: float
    resample_hz: int | None
    quantize_bits: int | None
    clip_dbfs: float | None


class RecordingPlan(NamedTuple):
    """Everything the five stages will do to one item, decided before any audio is read.

    `device` is a tuple of (slots, sos) pairs rather than one array because the response
    is per stem when it is coupled to per-stem distance — which is the default.
    """
    device: tuple
    rir: RirItemPlan | None
    envelopes: tuple
    bus: BusPlan | None
    dirty: DirtyPlan | None


# --- biquad primitives (RBJ Audio EQ Cookbook; minimum-phase by construction) ---
def _shelf_sos(kind: str, fs: float, f0: float, gain_db: float, q: float) -> np.ndarray:
    """One RBJ low/high shelf as a (1, 6) SOS row.

    Written out rather than pulled from a library because SciPy ships no shelf design and
    the only alternative in the tree is Pedalboard, which is GPLv3 (report §3.2) and which
    this module deliberately does not use.
    """
    amp = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * math.pi * f0 / fs
    cos_w0, sin_w0 = math.cos(w0), math.sin(w0)
    alpha = sin_w0 / (2.0 * q)
    two_sqrt_a_alpha = 2.0 * math.sqrt(amp) * alpha
    if kind == "low":
        b = [amp * ((amp + 1) - (amp - 1) * cos_w0 + two_sqrt_a_alpha),
             2 * amp * ((amp - 1) - (amp + 1) * cos_w0),
             amp * ((amp + 1) - (amp - 1) * cos_w0 - two_sqrt_a_alpha)]
        a = [(amp + 1) + (amp - 1) * cos_w0 + two_sqrt_a_alpha,
             -2 * ((amp - 1) + (amp + 1) * cos_w0),
             (amp + 1) + (amp - 1) * cos_w0 - two_sqrt_a_alpha]
    else:
        b = [amp * ((amp + 1) + (amp - 1) * cos_w0 + two_sqrt_a_alpha),
             -2 * amp * ((amp - 1) + (amp + 1) * cos_w0),
             amp * ((amp + 1) + (amp - 1) * cos_w0 - two_sqrt_a_alpha)]
        a = [(amp + 1) - (amp - 1) * cos_w0 + two_sqrt_a_alpha,
             2 * ((amp - 1) - (amp + 1) * cos_w0),
             (amp + 1) - (amp - 1) * cos_w0 - two_sqrt_a_alpha]
    return np.array([[b[0] / a[0], b[1] / a[0], b[2] / a[0],
                      1.0, a[1] / a[0], a[2] / a[0]]], dtype=np.float64)


def _peak_sos(fs: float, f0: float, gain_db: float, q: float) -> np.ndarray:
    """One RBJ peaking filter as a (1, 6) SOS row."""
    amp = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * math.pi * f0 / fs
    cos_w0 = math.cos(w0)
    alpha = math.sin(w0) / (2.0 * q)
    b = [1 + alpha * amp, -2 * cos_w0, 1 - alpha * amp]
    a = [1 + alpha / amp, -2 * cos_w0, 1 - alpha / amp]
    return np.array([[b[0] / a[0], b[1] / a[0], b[2] / a[0],
                      1.0, a[1] / a[0], a[2] / a[0]]], dtype=np.float64)


def _log_uniform(rng: np.random.Generator, low: float, high: float) -> float:
    """Log-uniform draw — the right prior for a frequency, as build_random_eq already does."""
    return float(10.0 ** rng.uniform(math.log10(low), math.log10(high)))


def build_device_response(rng: np.random.Generator, cfg: DeviceResponseConfig,
                          fs: float, distance_m: float) -> np.ndarray:
    """A capture-chain transfer function at `distance_m`, as an SOS cascade.

    Sections, in order: a second-order high-pass (capsule/preamp bottom end) · a broadband
    tilt (dark vs bright, the coarsest way two microphones differ) · a proximity low shelf
    whose gain falls off with distance · one to three capsule/off-axis resonances · an
    air/off-axis high shelf whose ATTENUATION grows with distance. Minimum phase by
    construction, so the stem keeps its transient alignment with the rest of the mix — and
    the target is the filtered stem, so the sum survives whatever this does (report §4.1).

    The tilt and the resonances are what make this a MICROPHONE model rather than a
    distance model: they are the part that does not vanish when the source is close, and
    measurement says the microphone is the corpus's real invariant (→ the class docstring).

    Args:
        rng: the item's Generator.
        cfg: the device_response sub-block.
        fs: sample rate.
        distance_m: sampled source-to-mic distance for THIS capture position.
    """
    def clip_db(value: float) -> float:
        return float(np.clip(value, -cfg.max_gain_db, cfg.max_gain_db))

    sections = [scipy.signal.butter(
        2, _log_uniform(rng, *cfg.highpass_hz), btype="high", fs=fs, output="sos")]

    # tilt: one draw, applied as +t/2 on one end and −t/2 on the other about a pivot, so
    # the broadband level is roughly preserved and only the SLOPE changes
    tilt_db = clip_db(rng.uniform(-cfg.tilt_max_db, cfg.tilt_max_db) / 2.0)
    pivot = _log_uniform(rng, *cfg.tilt_pivot_hz)
    sections.append(_shelf_sos("low", fs, pivot, tilt_db, q=0.5))
    sections.append(_shelf_sos("high", fs, pivot, -tilt_db, q=0.5))

    # proximity: 1.0 at/below the reference distance, linearly to 0.0 at the null
    span = max(1e-6, cfg.proximity_null_distance_m - cfg.proximity_ref_distance_m)
    proximity = float(np.clip(
        (cfg.proximity_null_distance_m - distance_m) / span, 0.0, 1.0))
    # the draw happens whatever the distance, so the RNG stream does not depend on which
    # room the bank happened to hand us — only the realised gain does
    proximity_db = clip_db(rng.uniform(0.0, cfg.proximity_max_db) * proximity)
    sections.append(_shelf_sos("low", fs, _log_uniform(rng, *cfg.proximity_shelf_hz),
                               proximity_db, q=0.7))

    peaks = int(rng.integers(cfg.capsule_peaks[0], cfg.capsule_peaks[1] + 1))
    for _ in range(peaks):
        sections.append(_peak_sos(
            fs, _log_uniform(rng, *cfg.capsule_hz),
            clip_db(rng.uniform(-cfg.capsule_max_db, cfg.capsule_max_db)),
            q=_log_uniform(rng, *cfg.capsule_q)))

    air = float(np.clip(distance_m / max(1e-6, cfg.air_full_distance_m), 0.0, 1.0))
    air_db = clip_db(-rng.uniform(0.0, cfg.air_max_db) * air)
    sections.append(_shelf_sos("high", fs, _log_uniform(rng, *cfg.air_shelf_hz),
                               air_db, q=0.7))
    return np.vstack(sections)


# --- the RIR bank -----------------------------------------------------------
class RirPool:
    """The synthetic RIR bank: a manifest plus lazily-loaded, worker-local kernels.

    Nothing is decoded at construction — only the parquet is read — so the main process
    pays a few milliseconds and each DataLoader worker builds its own cache after fork.
    `plan_item()` never touches this class's audio side, so provenance/verification runs
    work with no bank on disk at all.

    Two caches, deliberately different: every kernel is small (2 × 44,100 float32 ≈ 350 kB
    at a 1 s tail) so all of them may live in the dict, while one precomputed spectrum is
    2 × (nfft/2+1) complex64 ≈ 3.1 MB and only a handful are held (`fft_cache_size`).
    """

    def __init__(self, cfg: RirConfig, repo_root: Path, sample_rate: int,
                 chunk_frames: int) -> None:
        self.cfg = cfg
        self.sample_rate = int(sample_rate)
        self.chunk_frames = int(chunk_frames)
        manifest_path = repo_root / cfg.manifest
        self.audio_root = Path(cfg.audio_root)
        if not manifest_path.exists():
            raise FileNotFoundError(
                f"recording_aug.rir.prob={cfg.prob} > 0 but the RIR manifest "
                f"{manifest_path} does not exist. Build the bank first:\n"
                f"    uv run python scripts/build_rir_pool.py --out {self.audio_root}\n"
                "(the bank is data, not repo content — it lives under ~/storage)")
        if not self.audio_root.is_dir():
            raise FileNotFoundError(
                f"recording_aug.rir.audio_root={self.audio_root} does not exist while "
                f"rir.prob={cfg.prob} > 0 — the manifest is here but the WAVs are not.")

        # reset_index: row numbers are used as the plan's stable handle on a response and
        # are looked up with .iloc, so the label index must equal the positional one
        self.table = pd.read_parquet(manifest_path).reset_index(drop=True)
        missing_columns = {"room_id", "position", "path", "distance_m", "rt60_s",
                           "drr_db", "frames", "sample_rate"} - set(self.table.columns)
        if missing_columns:
            raise ValueError(f"{manifest_path} lacks columns {sorted(missing_columns)}")
        rates = set(self.table.sample_rate.unique())
        if rates != {self.sample_rate}:
            raise ValueError(f"RIR bank is at {sorted(rates)} Hz but the experiment runs "
                             f"at {self.sample_rate} Hz — resample the bank offline "
                             "(a band-limited response would act as a brick-wall filter)")
        self.tail_frames = int(self.table.frames.max())
        if self.tail_frames > int(round(cfg.max_tail_seconds * self.sample_rate)):
            raise ValueError(
                f"RIR bank holds responses of {self.tail_frames} frames "
                f"({self.tail_frames / self.sample_rate:.2f} s) but "
                f"rir.max_tail_seconds={cfg.max_tail_seconds}")
        # one fixed transform length for the whole bank keeps the spectrum cache usable
        self.nfft = int(scipy.fft.next_fast_len(self.chunk_frames + self.tail_frames - 1))

        self._rooms = list(self.table.room_id.unique())
        rows_by_room = {room: group.index.to_numpy()
                        for room, group in self.table.groupby("room_id", sort=False)}
        self._rows_by_room = rows_by_room
        # rooms grouped by RT60 band, and each room's rows grouped by distance band: both
        # resolved once at init so the per-item draw is two array lookups
        room_rt60 = {room: float(self.table.loc[rows, "rt60_s"].mean())
                     for room, rows in rows_by_room.items()}

        # The TOP band absorbs everything above it. With a strict `< high` on the last band
        # too, any room or position beyond the configured ceiling is silently undrawable, and
        # nothing warns: the guard below only fires when EVERY band is empty. Measured on
        # rir_pool_v1 with rt60_bands_s=[[.15,.35],[.35,.65],[.65,1.00]] — 6 of 48 rooms
        # (54 of 420 responses, 12.9%) sat above the 1.00 s ceiling, capping the reachable
        # T30 at 1.03 s while the bank reaches 1.37 s. Reverberation range is this arm's
        # headline axis, so losing its top third to a half-open interval is not acceptable.
        rt60_bands = [list(b) for b in cfg.rt60_bands_s]
        if rt60_bands:
            rt60_bands[-1][1] = float("inf")
        distance_bands = [list(b) for b in cfg.distance_bands_m]
        if distance_bands:
            distance_bands[-1][1] = float("inf")

        self.rooms_by_rt60_band = [
            [room for room in self._rooms if low <= room_rt60[room] < high]
            for low, high in rt60_bands]
        self.rows_by_room_distance: dict = {}
        for room, rows in rows_by_room.items():
            distances = self.table.loc[rows, "distance_m"].to_numpy()
            self.rows_by_room_distance[room] = [
                rows[(distances >= low) & (distances < high)]
                for low, high in distance_bands]

        # every response in the bank must now be reachable; if one is not, the bands have a
        # GAP rather than a ceiling, which is a config error worth failing on
        binned_rooms = sum(len(r) for r in self.rooms_by_rt60_band)
        if binned_rooms != len(self._rooms):
            missing = sorted(set(self._rooms) - {r for band in self.rooms_by_rt60_band
                                                 for r in band})
            raise ValueError(
                f"{len(missing)} room(s) in {manifest_path} fall in a GAP between "
                f"rt60_bands_s={cfg.rt60_bands_s}: {missing[:6]}"
                f"{'...' if len(missing) > 6 else ''} (their mean RT60s are "
                f"{[round(room_rt60[m], 3) for m in missing[:6]]})")
        usable = [band_index for band_index, rooms in
                  enumerate(self.rooms_by_rt60_band) if rooms]
        if not usable:
            raise ValueError(
                f"no room in {manifest_path} falls inside rt60_bands_s={cfg.rt60_bands_s} "
                f"(bank RT60 range {min(room_rt60.values()):.2f}–"
                f"{max(room_rt60.values()):.2f} s)")
        self.usable_rt60_bands = np.array(usable, dtype=np.intp)

        self._kernels: dict = {}
        self._spectra: dict = {}
        self._spectrum_order: list = []

    # --- draw side (no audio) ---
    def draw_room(self, rng: np.random.Generator) -> str:
        """One room: an RT60 band uniformly, then a room uniformly inside it."""
        band = int(self.usable_rt60_bands[rng.integers(self.usable_rt60_bands.size)])
        rooms = self.rooms_by_rt60_band[band]
        return str(rooms[rng.integers(len(rooms))])

    def draw_position(self, rng: np.random.Generator, room: str,
                      distance_band: int) -> int:
        """One source position inside `room`, from `distance_band` (or anywhere)."""
        rows = self.rows_by_room_distance[room][distance_band]
        if rows.size == 0:                    # this room has no position in that band
            rows = self._rows_by_room[room]
        return int(rows[rng.integers(rows.size)])

    def usable_distance_bands(self, room: str) -> np.ndarray:
        """Distance bands this room actually populates (every room populates ≥1)."""
        populated = [index for index, rows in
                     enumerate(self.rows_by_room_distance[room]) if rows.size]
        return np.array(populated or [0], dtype=np.intp)

    # --- realisation side (audio, worker-local) ---
    def kernel(self, row: int) -> np.ndarray:
        """The (2, tail_frames) response for one manifest row, zero-padded to the bank's
        common length so every spectrum shares one transform size."""
        cached = self._kernels.get(row)
        if cached is not None:
            return cached
        record = self.table.iloc[row]
        audio, rate = soundfile.read(self.audio_root / record.path, dtype="float32",
                                     always_2d=True)
        if rate != self.sample_rate:
            raise ValueError(f"{record.path}: RIR at {rate} Hz, bank claims "
                             f"{self.sample_rate} Hz")
        kernel = np.zeros((2, self.tail_frames), dtype=np.float32)
        audio = audio.T
        kernel[:, :audio.shape[1]] = audio[:2] if audio.shape[0] >= 2 else audio[:1]
        self._kernels[row] = kernel
        return kernel

    def spectrum(self, row: int) -> np.ndarray:
        """rfft of one response at the bank's fixed transform length, LRU-cached."""
        cached = self._spectra.get(row)
        if cached is not None:
            return cached
        spectrum = scipy.fft.rfft(self.kernel(row), n=self.nfft, axis=-1)
        self._spectra[row] = spectrum
        self._spectrum_order.append(row)
        while len(self._spectrum_order) > max(1, self.cfg.fft_cache_size):
            self._spectra.pop(self._spectrum_order.pop(0), None)
        return spectrum

    def convolve(self, stems: np.ndarray, rows: list) -> np.ndarray:
        """Batched FFT convolution: (n, 2, T) stems ⊛ one (2, L) response each.

        ONE forward transform over all 2n rows, one pointwise multiply, one inverse — not
        n calls to fftconvolve. Report §3.5 measured naive per-stem stereo fftconvolve at
        16–20 ms a source, i.e. 145–180 ms for nine, which alone exceeds the per-item
        budget; the batched form with precomputed response spectra is measured in
        tests/test_recording_aug.py's benchmark at a fraction of that.

        Channel-wise convolution (L with L, R with R) rather than downmix-then-spatialise:
        71955 stems carry their own close-mic stereo image and destroying it would be a
        second, unintended domain shift.

        Args:
            stems: (n, 2, T) float32 dry stems.
            rows:  n manifest row indices, one per stem (repeats are normal and cheap).
        """
        distinct = sorted(set(rows))
        spectra = scipy.fft.rfft(stems, n=self.nfft, axis=-1)            # (n, 2, F)
        if len(distinct) == 1:
            # the default scope. One (2, F) response BROADCAST over the stem axis — no
            # (n, 2, F) gather is materialised, which is both the cheapest path and the
            # one with no per-stem acoustic cue.
            spectra *= self.spectrum(distinct[0])
        else:
            index_of = {row: position for position, row in enumerate(distinct)}
            responses = np.stack([self.spectrum(row) for row in distinct])   # (d, 2, F)
            spectra *= responses[[index_of[row] for row in rows]]
        wet = scipy.fft.irfft(spectra, n=self.nfft, axis=-1)[..., :stems.shape[-1]]
        return np.ascontiguousarray(wet, dtype=np.float32)


# --- stage 3: level automation ----------------------------------------------
def draw_envelope(rng: np.random.Generator, cfg: LevelAutomationConfig,
                  segment_seconds: float, slots: tuple | None) -> EnvelopePlan:
    """Breakpoint times and gains for one linear-in-dB envelope.

    Breakpoints are the segment boundaries INCLUDING both ends, so a k-segment envelope
    has k+1 gains. Segment lengths come from a Dirichlet draw (sdx23-aimless's shape) with
    a floor of `min_segment_seconds`, and the segment count is clamped to what the window
    can actually hold — an 8 s chunk cannot carry five 2 s segments.
    """
    max_segments = max(1, int(segment_seconds // max(1e-6, cfg.min_segment_seconds)))
    low = max(1, min(int(cfg.segments_min), max_segments))
    high = max(low, min(int(cfg.segments_max), max_segments))
    count = int(rng.integers(low, high + 1))
    slack = segment_seconds - count * cfg.min_segment_seconds
    weights = rng.dirichlet(np.ones(count))
    lengths = cfg.min_segment_seconds + weights * max(0.0, slack)
    times = np.concatenate([[0.0], np.cumsum(lengths)])
    times[-1] = segment_seconds
    gains = rng.uniform(cfg.gain_db_min, cfg.gain_db_max, size=count + 1)
    return EnvelopePlan(times_s=tuple(float(t) for t in times),
                        gains_db=tuple(float(g) for g in gains), slots=slots)


def realise_envelope(plan: EnvelopePlan, frames: int, sample_rate: int) -> np.ndarray:
    """(frames,) float32 linear gain, interpolated linearly in dB between breakpoints."""
    grid = np.arange(frames, dtype=np.float32) / np.float32(sample_rate)
    decibels = np.interp(grid, np.asarray(plan.times_s), np.asarray(plan.gains_db))
    return (10.0 ** (decibels / 20.0)).astype(np.float32)


# --- stage 4: the limiter ---------------------------------------------------
def limiter_gain(mixture: np.ndarray, threshold_dbfs: float, attack_ms: float,
                 release_ms: float, sample_rate: int) -> np.ndarray:
    """Channel-linked peak-limiter gain curve for a (2, T) mixture → (T,) float32.

    Topology: instantaneous required gain → lookahead minimum filter → box smoothing →
    elementwise minimum with the required gain.

      * CHANNEL-LINKED (one curve from max|L|,|R|) because per-channel gain would move the
        stereo image, and the image is part of what the separator is being taught.
      * The minimum filter is the lookahead: the gain is already down before the transient
        arrives, so there is no attack overshoot to clip.
      * The box smooth gives the release shape. A recursive one-pole release cannot be
        vectorised and a Python loop over 352,800 samples is not affordable here.
      * The final elementwise minimum makes "never exceeds the threshold" UNCONDITIONAL —
        it does not depend on getting SciPy's filter-origin convention right, and it is
        what tests/test_recording_aug.py::test_limiter_never_overshoots checks.

    Written rather than taken from Pedalboard on purpose: report §3.2 flags Pedalboard as
    GPLv3, and a measured check of its Limiter showed it is not transparent below
    threshold, which would corrupt the m'/m ratio that the target allocation depends on.
    Returning the GAIN (not the limited signal) is what makes the allocation exact.

    Args:
        mixture: (2, T) float32.
        threshold_dbfs: ceiling, 0.0 = full scale (the LimitAug paper's setting).
        attack_ms: lookahead, in milliseconds.
        release_ms: recovery time, in milliseconds.
        sample_rate: samples per second.
    """
    threshold = float(10.0 ** (threshold_dbfs / 20.0))
    peak = np.abs(mixture).max(axis=0)
    required = np.ones_like(peak)
    over = peak > threshold
    if not over.any():
        return required
    required[over] = threshold / peak[over]
    attack = max(1, int(round(attack_ms * sample_rate / 1000.0)))
    release = max(1, int(round(release_ms * sample_rate / 1000.0)))
    window = attack + release + 1
    ducked = scipy.ndimage.minimum_filter1d(required, size=window, mode="nearest")
    smoothed = scipy.ndimage.uniform_filter1d(ducked, size=window, mode="nearest")
    return np.minimum(smoothed, required).astype(np.float32, copy=False)


def bus_ratio(mixture: np.ndarray, limited: np.ndarray, eps: float) -> np.ndarray:
    """r[t] = m'[t]/m[t] where the mixture has support, 1 elsewhere — report §4.3.

    The guard matters. Stems can be far larger than their sum (heterophonic cancellation),
    so where |m| collapses toward zero an unguarded ratio would scale genuine stem content
    to nothing and the residual correction would then have to reinstate all of it as a
    spike on one stem. Below the project's silence floor the bus has nothing to act on, so
    r = 1 is both correct and stable; the |m| < eps error it leaves behind is bounded by
    eps and is what `residual_correction` cleans up exactly.
    """
    ratio = np.ones_like(mixture)
    support = np.abs(mixture) > eps
    np.divide(limited, mixture, out=ratio, where=support)
    return ratio


def add_residual(stems: np.ndarray, residual: np.ndarray) -> None:
    """In place, add `residual` (2, T) to whichever stem is largest at each sample.

    Report §4.3's exact-sum rule. Which stem receives it barely matters — after the ratio
    allocation the residual is float rounding plus the sub-eps guard region — but putting
    it on the locally dominant stem keeps it masked rather than parked on a silent target.
    """
    if stems.shape[0] == 0:
        return
    dominant = np.abs(stems).argmax(axis=0)[None]               # (1, 2, T)
    current = np.take_along_axis(stems, dominant, axis=0)
    np.put_along_axis(stems, dominant, current + residual[None], axis=0)


# --- stage 5: dirty input ----------------------------------------------------
class NoisePool:
    """Environmental-noise bank for the dirty-input branch, manifest-driven like the RIRs.

    NO CORPUS IS SHIPPED OR ASSUMED. Report §5.1 is explicit that FSD50K's per-clip terms
    vary, MUSAN is per-source licensed and WHAM is CC BY-NC, so the honest default is "the
    experiment supplies its own pool and records where it came from". `noise_prob > 0`
    without a manifest raises rather than silently skipping the stage.
    """

    def __init__(self, cfg: DirtyInputConfig, repo_root: Path, sample_rate: int) -> None:
        if not cfg.noise_manifest:
            raise FileNotFoundError(
                "recording_aug.dirty_input.noise_prob > 0 but no noise_manifest is set. "
                "Point it at a parquet with columns path/frames/sample_rate and set "
                "noise_audio_root; no noise corpus ships with this repo (licensing — "
                "report §5.1).")
        manifest_path = repo_root / cfg.noise_manifest
        if not manifest_path.exists():
            raise FileNotFoundError(f"noise manifest {manifest_path} does not exist")
        self.table = pd.read_parquet(manifest_path)
        self.audio_root = Path(cfg.noise_audio_root or repo_root)
        self.sample_rate = int(sample_rate)

    def read(self, row: int, start: int, frames: int) -> np.ndarray:
        """(2, frames) float32 noise excerpt, mono duplicated (never naive-summed)."""
        record = self.table.iloc[row]
        audio, rate = soundfile.read(self.audio_root / record.path, start=int(start),
                                     frames=int(frames), dtype="float32", always_2d=True,
                                     fill_value=0.0)
        if rate != self.sample_rate:
            raise ValueError(f"{record.path}: noise at {rate} Hz, expected "
                             f"{self.sample_rate} Hz (resample the pool offline)")
        audio = audio.T
        if audio.shape[0] == 1:
            audio = np.repeat(audio, 2, axis=0)
        return np.ascontiguousarray(audio[:2])


def apply_resample_roundtrip(mixture: np.ndarray, sample_rate: int,
                             intermediate_hz: int) -> np.ndarray:
    """Down- then up-sample the mixture, keeping the frame count — soxr, not librosa.

    CLAUDE.md's lab convention is soundfile/soxr over librosa, and report §3.2 notes that
    the audiomentations resample path imports librosa, which is why this is reimplemented.
    """
    down = soxr.resample(mixture.T, sample_rate, intermediate_hz)
    back = soxr.resample(down, intermediate_hz, sample_rate).T
    out = np.zeros_like(mixture)
    width = min(out.shape[-1], back.shape[-1])
    out[:, :width] = back[:2, :width]
    return out


def apply_quantize(mixture: np.ndarray, bits: int) -> np.ndarray:
    """Uniform mid-tread quantization to `bits` — the consumer-format bit-depth axis."""
    step = np.float32(2.0 ** -(int(bits) - 1))
    return (np.round(mixture / step) * step).astype(np.float32)


def apply_clip(mixture: np.ndarray, clip_dbfs: float) -> np.ndarray:
    """Hard clip at `clip_dbfs` — an over-driven preamp, not a mastering limiter."""
    ceiling = np.float32(10.0 ** (clip_dbfs / 20.0))
    return np.clip(mixture, -ceiling, ceiling)


# --- the per-item draw (called from GugakMixDataset._plan_item) -------------
def plan_recording(rng: np.random.Generator, cfg: ResolvedRecordingConfig,
                   pool: "RirPool | None", noise: "NoisePool | None",
                   slots: tuple, cluster_of_slot: dict, sample_rate: int,
                   segment_seconds: float, chunk_frames: int) -> RecordingPlan | None:
    """Decide all five stages for one item. NO AUDIO IS READ AND NO FILE IS TOUCHED.

    DRAW ORDER IS A CONTRACT, exactly as it is for the mixing sampler: room → distances →
    device responses → automation → bus → dirty. The room is drawn BEFORE the device
    because the device response is a function of the stem's sampled distance, and a stage
    whose probability is 0 consumes nothing at all — the same convention
    `_draw_coherent_count` uses at p = 0, so an arm that adds one stage does not reshuffle
    the stages before it.

    Args:
        rng: the item's Generator, mid-stream (the mixing plan has already drawn).
        cfg: the resolved recording_aug block.
        pool: the RIR bank, or None when rir.prob == 0.
        noise: the noise bank, or None when dirty_input.noise_prob == 0.
        slots: the output slots this item actually filled, ascending.
        cluster_of_slot: slot → cluster index for clustered stems (absent = incoherent).
        sample_rate: samples per second.
        segment_seconds: the excerpt length, for the envelope time grid.
        chunk_frames: the excerpt length in frames, for the noise read offset.

    Returns:
        A RecordingPlan, or None when the block is off / every stage has probability 0 —
        in which case __getitem__ takes the untouched pre-change path.
    """
    if not cfg.any_stage_enabled or not slots:
        return None

    # --- stage 2 draw first: the distances it samples drive the device response ---
    rir_plan, distance_of_slot = _plan_rir(rng, cfg, pool, slots, cluster_of_slot)

    # --- stage 1: capture chain, one response per stem / cluster / mixture ---
    device = _plan_device(rng, cfg, slots, cluster_of_slot, distance_of_slot, sample_rate)

    # --- stage 3: level automation ---
    envelopes = []
    automation = cfg.automation
    if automation.mixbus_prob > 0.0 and rng.random() < automation.mixbus_prob:
        envelopes.append(draw_envelope(rng, automation, segment_seconds, None))
    if automation.stem_prob > 0.0:
        for slot in slots:
            if rng.random() < automation.stem_prob:
                envelopes.append(draw_envelope(rng, automation, segment_seconds, (slot,)))

    # --- stage 4: mix-bus loudness and limiting ---
    bus = _plan_bus(rng, cfg)

    # --- stage 5: dirty input (only reachable in clean_under_degraded_input) ---
    dirty = _plan_dirty(rng, cfg, noise, chunk_frames)

    if (not device and rir_plan is None and not envelopes and bus is None
            and dirty is None):
        return None
    return RecordingPlan(device=tuple(device), rir=rir_plan,
                         envelopes=tuple(envelopes), bus=bus, dirty=dirty)


def _plan_rir(rng: np.random.Generator, cfg: ResolvedRecordingConfig,
              pool: "RirPool | None", slots: tuple,
              cluster_of_slot: dict) -> tuple:
    """Room, source positions, and the slot → distance map the device stage reads."""
    rir_cfg = cfg.rir
    if rir_cfg.prob <= 0.0 or rng.random() >= rir_cfg.prob:
        return None, {}
    if pool is None:                       # unreachable: the dataset builds it when prob>0
        raise RuntimeError("rir.prob > 0 but no RIR bank was constructed")

    # rooms first (scope), then source positions inside each room (position_scope). Under
    # the defaults both collapse to one group, i.e. ONE kernel for the whole mixture.
    room_groups = _group_slots(rir_cfg.scope, slots, cluster_of_slot)
    assignments = []
    rooms = []
    for room_group in room_groups:
        room = pool.draw_room(rng)
        rooms.append(room)
        bands = pool.usable_distance_bands(room)
        # ONE mic placement per room: an ensemble sits at one distance from one mic, so
        # the band is a property of the room draw, never of the individual source
        band = int(bands[rng.integers(bands.size)])
        for position_group in _group_slots(_position_grain(rir_cfg.position_scope),
                                           room_group, cluster_of_slot):
            row = pool.draw_position(rng, room, band)
            record = pool.table.iloc[row]
            assignments.append(RirAssignment(row=row, slots=position_group,
                                             distance_m=float(record.distance_m),
                                             rt60_s=float(record.rt60_s),
                                             drr_db=float(record.drr_db)))
    distance_of_slot = {slot: assignment.distance_m
                        for assignment in assignments for slot in assignment.slots}
    return RirItemPlan(room_id="+".join(rooms), assignments=tuple(assignments),
                       target_mode=rir_cfg.target_mode), distance_of_slot


def _position_grain(position_scope: str) -> str:
    """position_scope → the slot-grouping scope `_group_slots` understands."""
    return {"shared": "per_mixture", "per_cluster": "per_cluster",
            "per_stem": "per_stem"}[position_scope]


def _group_slots(scope: str, slots: tuple, cluster_of_slot: dict) -> list:
    """Slots partitioned by capture identity: one group = one room / one source position.

    per_mixture = everything together, the default and the physical case (one ensemble,
    one space) · per_cluster = coherent clusters share and independently drawn incoherent
    stems stand alone · per_stem = every stem on its own, which introduces a train-only
    acoustic cue (→ RirConfig docstring) and exists as an ablation, not a default.
    """
    if scope == "per_mixture":
        return [tuple(slots)]
    if scope == "per_stem":
        return [(slot,) for slot in slots]
    by_cluster: dict = {}
    for slot in slots:
        key = ("cluster", cluster_of_slot[slot]) if slot in cluster_of_slot \
            else ("solo", slot)
        by_cluster.setdefault(key, []).append(slot)
    return [tuple(group) for group in by_cluster.values()]


def _plan_device(rng: np.random.Generator, cfg: ResolvedRecordingConfig, slots: tuple,
                 cluster_of_slot: dict, distance_of_slot: dict,
                 sample_rate: int) -> list:
    """One (slots, sos) pair per capture chain. Coupled to the room's sampled distance."""
    device_cfg = cfg.device
    if device_cfg.prob <= 0.0 or rng.random() >= device_cfg.prob:
        return []
    # the chain's grain FOLLOWS THE ROOM'S SOURCE POSITIONS, so "this stem was captured at
    # this position by this microphone" stays one consistent physical story rather than
    # two independently randomised ones. Under the defaults that is ONE response for the
    # whole mixture — one mic on one ensemble.
    room_groups = _group_slots(cfg.rir.scope, slots, cluster_of_slot)
    groups = [group for room_group in room_groups
              for group in _group_slots(_position_grain(cfg.rir.position_scope),
                                        room_group, cluster_of_slot)]
    out = []
    for group in groups:
        if device_cfg.couple_to_distance and group[0] in distance_of_slot:
            distance = distance_of_slot[group[0]]
        else:
            # no room this item (or coupling off): draw a plausible distance anyway, so
            # the proximity/air curves are still driven by one physical quantity
            distance = float(rng.uniform(*device_cfg.fallback_distance_m))
        out.append((group, build_device_response(rng, device_cfg, sample_rate, distance)))
    return out


def _plan_bus(rng: np.random.Generator, cfg: ResolvedRecordingConfig) -> BusPlan | None:
    """Pre-bus target loudness and the limiter decision (stage 4)."""
    limit_cfg = cfg.limit
    sampled = limit_cfg.loudness_mode == "sampled"
    if not sampled and limit_cfg.prob <= 0.0:
        return None
    target_lufs = (float(rng.normal(limit_cfg.target_lufs_mean, limit_cfg.target_lufs_std))
                   if sampled else math.nan)      # nan = keep the dataset's target_lufs
    release = None
    if limit_cfg.prob > 0.0 and rng.random() < limit_cfg.prob:
        release = float(rng.uniform(*limit_cfg.release_ms))
    if release is None and not sampled:
        return None
    return BusPlan(target_lufs=target_lufs, release_ms=release,
                   attack_ms=float(limit_cfg.attack_ms),
                   threshold_dbfs=float(limit_cfg.threshold_dbfs),
                   normalize_after_bus=bool(limit_cfg.normalize_after_bus),
                   residual_correction=bool(limit_cfg.residual_correction))


def _plan_dirty(rng: np.random.Generator, cfg: ResolvedRecordingConfig,
                noise: "NoisePool | None", chunk_frames: int) -> DirtyPlan | None:
    """Stage 5's decisions, in the report's order: noise → resample → quantize → clip."""
    dirty_cfg = cfg.dirty
    if not dirty_cfg.any_enabled:
        return None
    noise_row, noise_start, snr = None, 0, math.nan
    if dirty_cfg.noise_prob > 0.0 and rng.random() < dirty_cfg.noise_prob:
        if noise is None:
            raise RuntimeError("dirty_input.noise_prob > 0 but no noise bank was built")
        noise_row = int(rng.integers(len(noise.table)))
        frames = int(noise.table.iloc[noise_row].frames)
        noise_start = int(rng.integers(max(1, frames - chunk_frames + 1)))
        snr = float(rng.uniform(*dirty_cfg.noise_snr_db))
    resample_hz = None
    if dirty_cfg.resample_prob > 0.0 and rng.random() < dirty_cfg.resample_prob:
        resample_hz = int(dirty_cfg.intermediate_rates[
            rng.integers(len(dirty_cfg.intermediate_rates))])
    bits = None
    if dirty_cfg.quantize_prob > 0.0 and rng.random() < dirty_cfg.quantize_prob:
        bits = int(dirty_cfg.bit_depths[rng.integers(len(dirty_cfg.bit_depths))])
    clip_dbfs = None
    if dirty_cfg.clip_prob > 0.0 and rng.random() < dirty_cfg.clip_prob:
        clip_dbfs = float(rng.uniform(*dirty_cfg.clip_dbfs))
    if noise_row is None and resample_hz is None and bits is None and clip_dbfs is None:
        return None
    return DirtyPlan(noise_row=noise_row, noise_start=noise_start, noise_snr_db=snr,
                     resample_hz=resample_hz, quantize_bits=bits, clip_dbfs=clip_dbfs)
